"""last_read_message_id

Revision ID: 3fc3360164dc
Revises: ca294a33443d
Create Date: 2025-11-10 12:30:25.550226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fc3360164dc'
down_revision: Union[str, Sequence[str], None] = 'ca294a33443d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_members', sa.Column('last_read_message_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'conversation_members', 'messages', ['last_read_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversation_members', type_='foreignkey')
    op.drop_column('conversation_members', 'last_read_message_id')
    # ### end Alembic commands ###
